[package]
name = "stepper_lib"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "stepper_lib"
path = "src/lib.rs"

[[bin]]
name = "test_gcode"
path = "bin/test_gcode.rs"

[dependencies]
gpio = "0.4.1"
gcode = "0.6.1"