[package]
name = "stepper_lib"
version = "0.3.9"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "stepper_lib"
path = "src/lib.rs"

# Tests
[[bin]]
name = "test_gcode"
path = "bin/test_gcode.rs"

[[bin]]
name = "test_repeat"
path = "bin/test_repeat.rs"

[[bin]]
name = "test_step"
path = "bin/test_step.rs"

[[bin]]
name = "test_steps"
path = "bin/test_steps.rs"
# //

[dependencies]
gpio = "0.4.1"
gcode = "0.6.1"